import joplin from 'api';
import { MenuItemLocation, ToolbarButtonLocation, ContentScriptType, ModelType } from 'api/types';

const LOG = '[Univer]';
const SHEET_ID_PREFIX = 'sheet-';
const FENCE_NOTICE = '<!-- generated by joplin-univer-plugin: do not edit, edit via the spreadsheet popup -->';
const FENCE_WARNING = '> ⚠️ **Read-only mirror of the spreadsheet.** Edits made here will be overwritten the next time the spreadsheet is saved.';

// Run a registration step and log success/failure without aborting the rest of onStart.
async function step(name: string, fn: () => Promise<void>): Promise<void> {
	try {
		await fn();
		console.info(LOG, name, 'OK');
	} catch (error) {
		console.error(LOG, name, 'FAILED', error);
	}
}

function escapeRegExp(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function colIndexToLetters(n: number): string {
	let s = '';
	let x = n;
	while (x >= 0) {
		s = String.fromCharCode(65 + (x % 26)) + s;
		x = Math.floor(x / 26) - 1;
	}
	return s;
}

function cellToMarkdownText(cell: any): string {
	if (cell == null) return '';
	const raw = (cell.v != null ? cell.v : (cell.f != null ? cell.f : ''));
	return String(raw)
		.replace(/\\/g, '\\\\')
		.replace(/\|/g, '\\|')
		.replace(/\r?\n/g, '<br>');
}

// Color for .univer-formula is set in contentScript.ts CSS so we can vary it
// by light/dark mode. No inline style here — the bare class is plenty.
const FORMULA_SPAN_OPEN = '<span class="univer-formula">';
const FORMULA_SPAN_CLOSE = '</span>';
const FORMULA_GLYPH = 'ƒ ';

function wrapFormulaCellMarkdown(text: string): string {
	return FORMULA_SPAN_OPEN + FORMULA_GLYPH + text + FORMULA_SPAN_CLOSE;
}

function sheetSnapshotToMarkdownTable(snapshot: any): string {
	if (!snapshot || !snapshot.sheets) return '_(empty spreadsheet)_';
	const firstId = (snapshot.sheetOrder && snapshot.sheetOrder[0]) || Object.keys(snapshot.sheets)[0];
	const sheet = snapshot.sheets[firstId];
	const cellData = (sheet && sheet.cellData) || {};

	let maxRow = -1;
	let maxCol = -1;
	for (const rk of Object.keys(cellData)) {
		const r = parseInt(rk, 10);
		if (isNaN(r)) continue;
		const row = cellData[rk];
		if (!row) continue;
		for (const ck of Object.keys(row)) {
			const c = parseInt(ck, 10);
			if (isNaN(c)) continue;
			const cell = row[ck];
			const text = cellToMarkdownText(cell);
			if (text === '') continue;
			if (r > maxRow) maxRow = r;
			if (c > maxCol) maxCol = c;
		}
	}

	if (maxRow < 0 || maxCol < 0) return '_(empty spreadsheet)_';

	const getCellRaw = (r: number, c: number): any => {
		const row = cellData[r] || cellData[String(r)];
		if (!row) return null;
		return row[c] != null ? row[c] : row[String(c)];
	};

	const renderCell = (r: number, c: number): string => {
		const cell = getCellRaw(r, c);
		const text = cellToMarkdownText(cell);
		if (text === '') return '';
		if (cell && cell.f != null) {
			return wrapFormulaCellMarkdown(text);
		}
		return text;
	};

	// Headers are always synthetic column letters (A, B, C, ...) matching the
	// spreadsheet's own column gutter. Sheet row 0 is treated as data, not a
	// header — that way the markdown table mirrors the spreadsheet 1:1.
	const headerRow: string[] = [];
	for (let c = 0; c <= maxCol; c++) headerRow.push(colIndexToLetters(c));

	const lines: string[] = [];
	lines.push('| ' + headerRow.join(' | ') + ' |');
	lines.push('| ' + headerRow.map(() => '---').join(' | ') + ' |');

	for (let r = 0; r <= maxRow; r++) {
		const row: string[] = [];
		for (let c = 0; c <= maxCol; c++) row.push(renderCell(r, c));
		lines.push('| ' + row.join(' | ') + ' |');
	}

	return lines.join('\n');
}

function buildFencedBlock(sheetId: string, snapshot: any): string {
	const table = sheetSnapshotToMarkdownTable(snapshot);
	return [
		`<!-- univer-sheet:start id=${sheetId} layout=data -->`,
		FENCE_NOTICE,
		FENCE_WARNING,
		'',
		table,
		`<!-- univer-sheet:end id=${sheetId} -->`,
	].join('\n');
}

function upsertFencedBlock(noteBody: string, sheetId: string, fencedBlock: string): string {
	const body = noteBody == null ? '' : noteBody;
	const idEsc = escapeRegExp(sheetId);
	// Match both legacy fences (no layout attr) and new fences (layout=...).
	const fenceRe = new RegExp(
		`<!--\\s*univer-sheet:start\\s+id=${idEsc}(?:\\s+[^>]*)?\\s*-->[\\s\\S]*?<!--\\s*univer-sheet:end\\s+id=${idEsc}\\s*-->`,
		'g'
	);
	if (fenceRe.test(body)) {
		return body.replace(fenceRe, fencedBlock);
	}
	const linkRe = new RegExp(`\\(univer-sheet://${idEsc}\\)`);
	const m = linkRe.exec(body);
	if (m) {
		const lineEnd = body.indexOf('\n', m.index);
		const insertAt = lineEnd === -1 ? body.length : lineEnd;
		const prefix = body.slice(0, insertAt);
		const suffix = body.slice(insertAt);
		return prefix + '\n\n' + fencedBlock + (suffix.startsWith('\n') ? '' : '\n') + suffix;
	}
	return body + (body.endsWith('\n') ? '' : '\n') + '\n' + fencedBlock + '\n';
}


async function updateNoteWithFencedTable(noteId: string, sheetId: string, snapshot: any, opts?: { waitForLink?: boolean }): Promise<void> {
	const waitForLink = !!(opts && opts.waitForLink);
	const linkSubstr = `(univer-sheet://${sheetId})`;
	const fenceStartSubstr = `<!-- univer-sheet:start id=${sheetId} -->`;
	try {
		let note: any = null;
		// When invoked right after insertText, the editor may not have flushed the
		// new link to the database yet. Poll briefly so upsertFencedBlock can anchor
		// the fence below the link instead of falling back to end-of-note.
		const maxAttempts = waitForLink ? 20 : 1;
		for (let i = 0; i < maxAttempts; i++) {
			note = await joplin.data.get(['notes', noteId], { fields: ['id', 'body'] });
			const body = note.body || '';
			if (!waitForLink || body.indexOf(linkSubstr) !== -1 || body.indexOf(fenceStartSubstr) !== -1) break;
			await new Promise(res => setTimeout(res, 100));
		}
		const newBody = upsertFencedBlock(note.body || '', sheetId, buildFencedBlock(sheetId, snapshot));
		if (newBody !== note.body) {
			await joplin.data.put(['notes', noteId], null, { body: newBody });
		}
	} catch (error) {
		console.error(LOG, 'updateNoteWithFencedTable failed:', error);
	}
}

/**
 * Joplin Univer Plugin
 * Embeds interactive Univer spreadsheets within Joplin notes
 * VERSION: 2.4.0 - Dialog-based editing with userData storage, RTE support, formulas, row/col manipulation
 */
joplin.plugins.register({
	onStart: async function() {
		console.info(LOG, '=== UNIVER PLUGIN v2.4.0 STARTING ===');

		let dialogHandle = '';

		await step('create dialog', async () => {
			dialogHandle = await joplin.views.dialogs.create('univerDialog');
			await joplin.views.dialogs.setFitToContent(dialogHandle, false);
			await joplin.views.dialogs.setButtons(dialogHandle, [
				{ id: 'save', title: 'Save & Close' },
				{ id: 'cancel', title: 'Cancel' },
			]);
			// addScript is one-time at registration; setHtml is per-open.
			await joplin.views.dialogs.addScript(dialogHandle, './dialogScript.js');
		});

		await step('register MarkdownItPlugin content script', async () => {
			await joplin.contentScripts.register(
				ContentScriptType.MarkdownItPlugin,
				'univerSheet',
				'./contentScript.js'
			);
		});

		await step('register CodeMirrorPlugin content script', async () => {
			await joplin.contentScripts.register(
				ContentScriptType.CodeMirrorPlugin,
				'univerSheetCodeMirror',
				'./contentScriptTinyMCE.js'
			);
		});

		const messageSources = [
			{ id: 'univerSheet', label: 'MarkdownIt' },
			{ id: 'univerSheetCodeMirror', label: 'CodeMirror' },
		];
		for (const { id, label } of messageSources) {
			await step(`register ${label} message handler`, async () => {
				await joplin.contentScripts.onMessage(id, async (sheetId: string) => {
					if (typeof sheetId === 'string' && sheetId.startsWith(SHEET_ID_PREFIX)) {
						console.info(LOG, `open from ${label} click:`, sheetId);
						await joplin.commands.execute('openUniverSheet', sheetId);
					} else {
						console.warn(LOG, `invalid sheet id from ${label}:`, sheetId);
					}
				});
			});
		}

		await step('register insertUniverSheet command', async () => {
			await joplin.commands.register({
				name: 'insertUniverSheet',
				label: 'Insert Univer Spreadsheet',
				iconName: 'fas fa-table',
				execute: async () => {
					try {
						const note = await joplin.workspace.selectedNote();
						if (!note) {
							await joplin.views.dialogs.showMessageBox('Please select a note first');
							return;
						}

						const sheetId = `${SHEET_ID_PREFIX}${Date.now()}`;
						const defaultData = {
							id: sheetId,
							name: 'Spreadsheet',
							sheetOrder: ['sheet-01'],
							appVersion: '0.1.0',
							locale: 'en-US',
							styles: {},
							sheets: {
								'sheet-01': {
									id: 'sheet-01',
									name: 'Sheet1',
									cellData: {},
									rowCount: 100,
									columnCount: 26,
									defaultColumnWidth: 93,
									defaultRowHeight: 27,
								},
							},
						};

						await joplin.data.userDataSet(ModelType.Note, note.id, `univer_${sheetId}`, defaultData);

						// Use univer-sheet:// instead of joplin://x-callback-url/ to avoid
						// Joplin's internal callback URL handler intercepting the link.
						// Insert only the link via insertText — Joplin's editors strip HTML
						// comments from inserted text, so the fenced block is added separately
						// via the data API which preserves comments verbatim.
						const markdown = `\n[📈 Click to Open Spreadsheet](univer-sheet://${sheetId})\n`;
						await joplin.commands.execute('insertText', markdown);
						await updateNoteWithFencedTable(note.id, sheetId, defaultData, { waitForLink: true });
					} catch (error) {
						console.error(LOG, 'insertUniverSheet failed:', error);
						await joplin.views.dialogs.showMessageBox(`Failed to insert spreadsheet: ${error.message}`);
					}
				},
			});
		});

		await step('register openUniverSheet command', async () => {
			await joplin.commands.register({
				name: 'openUniverSheet',
				label: 'Open Univer Spreadsheet',
				execute: async (sheetIdParam?: string) => {
					try {
						let sheetId = sheetIdParam;

						if (!sheetId) {
							const selectedText = await joplin.commands.execute('selectedText');
							if (selectedText) {
								const match = selectedText.match(/sheet-\d+/);
								if (match) sheetId = match[0];
							}
						}

						if (!sheetId) {
							await joplin.views.dialogs.showMessageBox(
								'No spreadsheet ID found.\n\n' +
								'Please select the sheet ID text (e.g., sheet-1234567890) and try again.'
							);
							return;
						}

						const note = await joplin.workspace.selectedNote();
						if (!note) {
							await joplin.views.dialogs.showMessageBox('No note selected');
							return;
						}

						const data: any = await joplin.data.userDataGet(ModelType.Note, note.id, `univer_${sheetId}`);
						if (!data) {
							await joplin.views.dialogs.showMessageBox('Spreadsheet data not found. It may have been deleted or the note may have changed.');
							return;
						}

						let dataObj: any = data;
						if (typeof dataObj === 'string') {
							try { dataObj = JSON.parse(dataObj); } catch(e) { /* use as-is */ }
						}

						if (!dataObj || typeof dataObj !== 'object' || !dataObj.sheets) {
							console.error(LOG, 'invalid spreadsheet data:', dataObj);
							await joplin.views.dialogs.showMessageBox(
								'Spreadsheet data is corrupted or in an unexpected format.\n\n' +
								'Data type: ' + typeof dataObj
							);
							return;
						}

						// One-way sync only: the spreadsheet is the source of truth. The
						// fenced markdown table is a read-only mirror — any edits the user
						// makes there are ignored and overwritten on save. We don't try to
						// reconcile the markdown body here; updateNoteWithFencedTable on
						// save (and on dialog open below if the fence is missing) keeps the
						// note in sync with the snapshot.

						const dataName = dataObj.name || 'Spreadsheet';
						const sheetCount = (dataObj.sheetOrder && dataObj.sheetOrder.length) || 1;

						// HTML must not contain inline <script> (CSP). Data passes via hidden div;
						// dialogScript.js was registered once via addScript() in onStart.
						const html = `
							<style>
								body {
									margin: 0;
									padding: 20px;
									font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
									background: #f6f8fa;
								}
								.header {
									background: white;
									padding: 16px;
									border-radius: 6px;
									margin-bottom: 16px;
									box-shadow: 0 1px 3px rgba(0,0,0,0.1);
								}
								.header h2 { margin: 0 0 8px 0; color: #24292f; }
								.header p { margin: 0; color: #57606a; font-size: 14px; }
								.spreadsheet-container {
									background: white;
									border-radius: 6px;
									padding: 16px;
									box-shadow: 0 1px 3px rgba(0,0,0,0.1);
									min-height: 400px;
									overflow: auto;
								}
								table { width: 100%; border-collapse: collapse; font-size: 13px; }
								th, td { border: 1px solid #d0d7de; padding: 6px 10px; text-align: left; }
								th { background: #f6f8fa; font-weight: 600; color: #57606a; }
								input {
									width: 100%; border: none; background: transparent;
									font-family: inherit; font-size: inherit; padding: 0;
									box-sizing: border-box;
								}
								input:focus { outline: 2px solid #0969da; outline-offset: -2px; }
								.formula-cell { background: #f0f7ff; }
								.formula-cell input { color: #0550ae; }
								/* Highlight the cell whose reference is "live" while typing a formula */
								td.ref-target { outline: 2px dashed #1f883d; outline-offset: -2px; background: #dcffe4; }
								.info {
									margin-top: 16px; padding: 12px;
									background: #ddf4ff; border-radius: 6px;
									color: #0969da; font-size: 13px;
								}
								#spreadsheet-data { display: none; }
							</style>
							<div class="header">
								<h2>📊 ${dataName}</h2>
								<p>Sheet ID: ${sheetId} • ${sheetCount} sheet(s)</p>
							</div>
							<div class="spreadsheet-container">
								<form name="spreadsheet">
									<div id="spreadsheet-editor"><p style="color:#888">Loading spreadsheet...</p></div>
									<input type="hidden" name="state" id="spreadsheet-state" value="">
								</form>
							</div>
							<div class="info">
								💡 Edit cells directly. Use formulas like =SUM(A1:A5), =AVERAGE, =IF. Click "Save &amp; Close" to persist.
							</div>
							<div id="spreadsheet-data">${JSON.stringify(dataObj).replace(/</g, '\\u003c')}</div>
						`;

						await joplin.views.dialogs.setHtml(dialogHandle, html);
						const result = await joplin.views.dialogs.open(dialogHandle);

						if (result.id === 'save') {
							const formData = result.formData;
							let updatedData: any = dataObj;

							// Preferred path: dialogScript.js writes the authoritative in-memory
							// state (including formula cells {f, v}) into a hidden input on every
							// edit. Parse that to preserve formulas exactly as entered.
							const stateStr = formData && formData.spreadsheet && formData.spreadsheet.state;
							let stateParsed: any = null;
							if (stateStr) {
								try { stateParsed = JSON.parse(stateStr); } catch (e) {
									console.warn(LOG, 'failed to parse dialog state, falling back to cell merge:', e);
								}
							}

							if (stateParsed && stateParsed.sheets) {
								updatedData = stateParsed;
							} else if (formData && formData.spreadsheet) {
								// Fallback: merge per-cell form inputs into existing data. Only used
								// if the hidden state input wasn't populated for some reason.
								const firstSheetId = (updatedData.sheetOrder && updatedData.sheetOrder[0]) || Object.keys(updatedData.sheets)[0];
								const existingCellData = updatedData.sheets[firstSheetId].cellData || {};
								const newCellData: any = {};

								for (const [rowKey, rowData] of Object.entries(existingCellData)) {
									const row = parseInt(rowKey);
									if (!isNaN(row)) {
										newCellData[row] = {};
										for (const [colKey, cellVal] of Object.entries(rowData as any)) {
											const col = parseInt(colKey);
											if (!isNaN(col) && cellVal) {
												newCellData[row][col] = cellVal;
											}
										}
									}
								}

								for (const [key, value] of Object.entries(formData.spreadsheet)) {
									const match = key.match(/^cell-(\d+)-(\d+)$/);
									if (match) {
										const row = parseInt(match[1]);
										const col = parseInt(match[2]);
										if (!newCellData[row]) newCellData[row] = {};
										const existing = newCellData[row][col];
										if (!existing || !existing.f) {
											if (value !== '') {
												newCellData[row][col] = { v: value };
											} else {
												delete newCellData[row][col];
											}
										}
									}
								}
								updatedData.sheets[firstSheetId].cellData = newCellData;
							}

							const jsonStr = JSON.stringify(updatedData);
							const MAX_JSON_SIZE = 5 * 1024 * 1024;
							if (jsonStr.length > MAX_JSON_SIZE) {
								await joplin.views.dialogs.showMessageBox(
									'Spreadsheet data is too large to save (' +
									Math.round(jsonStr.length / 1024) + ' KB).\n\n' +
									'Maximum allowed size is 5 MB. Please reduce the amount of data.'
								);
								return;
							}

							await joplin.data.userDataSet(ModelType.Note, note.id, `univer_${sheetId}`, updatedData);
							await updateNoteWithFencedTable(note.id, sheetId, updatedData);
						}

					} catch (error) {
						console.error(LOG, 'openUniverSheet failed:', error);
						await joplin.views.dialogs.showMessageBox(`Failed to open editor: ${error.message}`);
					}
				},
			});
		});

		await step('create toolbar button', async () => {
			await joplin.views.toolbarButtons.create(
				'univerSheetButton',
				'insertUniverSheet',
				ToolbarButtonLocation.EditorToolbar
			);
		});

		await step('create menu item', async () => {
			await joplin.views.menuItems.create(
				'univerSheetMenu',
				'insertUniverSheet',
				MenuItemLocation.Tools,
				{ accelerator: 'CmdOrCtrl+Shift+U' }
			);
		});

		console.info(LOG, 'plugin registration complete');
	},
});
